/**
 * CovidCare API
 * CovidCare API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ContactDTO { 
    contactNo?: number;
    contactTypeId?: number;
    contactTypeName?: string;
    email?: string;
    hospitalId?: number;
    hospitalName?: string;
    id?: number;
    lastModified: Date;
    lastModifiedBy: string;
    name: string;
    supplierId?: number;
    supplierName?: string;
}
