/**
 * CovidCare API
 * CovidCare API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 import { BedTypeDTO } from './bedTypeDTO';
 import { InventoryMasterDTO } from './inventoryMasterDTO';

export interface DistrictDTO {
    deleted?: boolean;
    id?: number;
    lastModified: Date;
    lastModifiedBy: string;
    name: string;
    stateId?: number;
    stateName?: string;
    divisionId?: number;
    divisionName?: string;
    bedTypes?: Array<BedTypeDTO> //Caclulated
    inventoryMaster?: Array<InventoryMasterDTO> //Caclulated
    calculations?:any;//Caclulated
}
