/**
 * CovidCare API
 * CovidCare API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 import { DistrictDTO } from './districtDTO';
export interface DivisionDTO {
    deleted?: boolean;
    id?: number;
    lastModified: Date;
    lastModifiedBy: string;
    name: string;
    districts?:DistrictDTO[] //calculated;
    breakpoint?:number;//calculated
    bgcolur?:String;//calculated
}
