/**
 * CovidCare API
 * CovidCare API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BedInventoryDTO } from './bedInventoryDTO';
import { InventoryDTO } from './inventoryDTO';
import { CalculationDTO } from './calculationDTO';
import { SupplierDTO } from './supplierDTO';


export interface HospitalDTO {
    address1?: string;
    address2?: string;
    area?: string;
    bedInventory?: Array<BedInventoryDTO>;
    category?: HospitalDTO.CategoryEnum;
    cityId?: number;
    cityName?: string;
    contactNo?: string;
    districtId?: number;
    districtName?: string;
    docCount?: number;
    email?: string;
    hospitalId?: number;
    hospitalTypeId?: number;
    hospitalTypeName?: string;
    id?: number;
    inventory?: Array<InventoryDTO>;
    lastModified?: Date;
    lastModifiedBy?: string;
    latitude?: string;
    longitude?: string;
    municipalCorpId?: number;
    municipalCorpName?: string;
    name?: string;
    nodalPerson?: string;
    nodalPersonContactNo?: string;
    pinCode?: string;
    registrationNo?: string;
    stateId?: number;
    stateName?: string;
    statusInd?: HospitalDTO.StatusIndEnum;
    subCategory?: HospitalDTO.SubCategoryEnum;
    suppliers?: Array<SupplierDTO>;
    talukaId?: number;
    talukaName?: string;
    calclulations?:CalculationDTO; //calculated
}
export namespace HospitalDTO {
    export type CategoryEnum = 'CENTRAL' | 'GOVT' | 'PRIVATE';
    export const CategoryEnum = {
        CENTRAL: 'CENTRAL' as CategoryEnum,
        GOVT: 'GOVT' as CategoryEnum,
        PRIVATE: 'PRIVATE' as CategoryEnum
    };
    export type StatusIndEnum = 'A' | 'I' | 'D';
    export const StatusIndEnum = {
        A: 'A' as StatusIndEnum,
        I: 'I' as StatusIndEnum,
        D: 'D' as StatusIndEnum
    };
    export type SubCategoryEnum = 'FREE' | 'MPJAY' | 'CHARGEABLE' | 'TRUST';
    export const SubCategoryEnum = {
        FREE: 'FREE' as SubCategoryEnum,
        MPJAY: 'MPJAY' as SubCategoryEnum,
        CHARGEABLE: 'CHARGEABLE' as SubCategoryEnum,
        TRUST: 'TRUST' as SubCategoryEnum
    };
}
