/**
 * CovidCare API
 * CovidCare API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface  InventoryMasterDTO {
    calulateVolume?: number;
    deleted?: boolean;
    description?: string;
    dimensions?: string;
    id?: number;
    inventoryTypeId?: number;
    inventoryTypeName?: string;
    lastModified?: Date;
    lastModifiedBy?: string;
    name: string;
    subTypeInd?: string;
    unit: string;
    volume?: number;
    totalReq?:number;//calculated
    available?:number;//calculated
}
