/**
 * CovidCare API
 * CovidCare API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 import { TransactionsDTO } from './transactionsDTO';

export interface InventoryDTO {
    capcity?: number;
    hospitalId?: number;
    hospitalName?: string;
    id?: number;
    installedCapcity?: number;
    inventoryMasterId?: number;
    inventoryMasterName?: string;
    inventoryTypeId?: number;
    inventoryTypeName?: string;
    lastModified?: Date;
    lastModifiedBy?: string;
    stock?: number;
    supplierId?: number;
    supplierName?: string;
    transactions?: Array<TransactionsDTO>; //CALCULATED
    supplierType?: string; //CALCULATED
}
