export interface patientMonitorFormPMDTO{
  auditId: number
  bedNo: number
  dateOfAdmission: string
  drName: string
  eightToTenPM: number
  fourToSixAM: number
  freeField1: string
  freeField2: string
  freeField3: string
  freeField4: string
  id: number
  lastModified: string
  lastModifiedBy: string
  nurseName: string
  oxyEightToTenPM: number
  oxyFourToSixAM: number
  oxySixToEightPM: number
  oxyTenToTwelvePM: number
  oxyTwelveToTwoAM: number
  oxyTwoToFourAM: number
  oxygenType: string
  patientName: string
  sixToEightPM: number
  tenToTwelvePM: number
  twelveToTwoAM: number
  twoToFourAM: number
  wardNo: number
}
