/**
 * CovidCare API
 * CovidCare API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SecurityPermissionDTO } from './securityPermissionDTO';
import { SecurityRoleDTO } from './securityRoleDTO';


export interface SecurityUserDTO {
    id?: number;
    authorities?: Array<string>;
    email?: string;
    firstName?: string;
    imageUrl?: string;
    langKey?: string;
    lastName?: string;
    login?: string;
    mobileNo?:number;
    activated?:number;
    passwordHash?:string;
    securityRoles?:SecurityRoleDTO[]
    conpassword?:string;//calculated
}
