/**
 * CovidCare API
 * CovidCare API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InventoryDTO } from './inventoryDTO';
import { CalculationDTO } from './calculationDTO';

export interface SupplierDTO {
  address1?: string;
  address2?: string;
  area?: string;
  cityId?: number;
  cityName?: string;
  contactNo?: string;
  deleted?: boolean;
  districtId?: number;
  districtName?: string;
  email?: string;
  id?: number;
  inventory?: Array<InventoryDTO>;
  inventoryTypeId?: number;
  inventoryTypeName?: string;
  lastModified?: Date;
  lastModifiedBy?: string;
  latitude?: string;
  longitude?: string;
  name?: string;
  pinCode?: string;
  registrationNo?: string;
  stateId?: number;
  stateName?: string;
  supplierType?: SupplierDTO.SupplierTypeEnum;
  talukaId?: number;
  talukaName?: string;
  statusInd?: SupplierDTO.StatusIndEnum;
  calclulations?: CalculationDTO; //calculated
}
export namespace SupplierDTO {
  export type StatusIndEnum = 'A' | 'I' | 'D';
  export const StatusIndEnum = {
    A: 'A' as StatusIndEnum,
    I: 'I' as StatusIndEnum,
    D: 'D' as StatusIndEnum,
  };
  export type SupplierTypeEnum = 'REFILLER' | 'MANUFACTURER' | 'DEALER' | 'DISTRIBUTOR' | 'INDUSTRY';
  export const SupplierTypeEnum = {
    REFILLER: 'REFILLER' as SupplierTypeEnum,
    MANUFACTURER: 'MANUFACTURER' as SupplierTypeEnum,
    DEALER: 'DEALER' as SupplierTypeEnum,
    DISTRIBUTOR: 'DISTRIBUTOR' as SupplierTypeEnum,
    INDUSTRY: 'INDUSTRY' as SupplierTypeEnum,
  };
}
