/**
 * CovidCare API
 * CovidCare API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 import { InventoryDTO } from './inventoryDTO';


export interface TransactionsDTO {
    comment?: string;
    hospitalId?: number;
    hospitalName?: string;
    id?: number;
    inventoryId?: number;
    inventoryMasterId?: number;
    inventoryMasterName?: string;
    lastModified?: Date;
    lastModifiedBy?: string;
    status?: TransactionsDTO.StatusEnum;
    stockProvided?: number;
    stockReq?: number;
    supplierId?: number;
    supplierName?: string;
    supplierInventory?: InventoryDTO; //calulated
    hospitalInventory?: InventoryDTO;//calulated
}
export namespace TransactionsDTO {
    export type StatusEnum = 'OPEN' | 'TRANSIT' | 'CANCELLED' | 'RECEIVED';
    export const StatusEnum = {
        OPEN: 'OPEN' as StatusEnum,
        TRANSIT: 'TRANSIT' as StatusEnum,
        CANCELLED: 'CANCELLED' as StatusEnum,
        RECEIVED: 'RECEIVED' as StatusEnum
    };
}
