/**
 * CovidCare API
 * CovidCare API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TripDetailsDTO {
    id?: number;
    stockSent?: number;
    stockRec?: number;
    status?: string;
    createdDate?: Date;
    createdBy?: string;
    lastModified?: Date;
    lastModifiedBy?: string;
    hospitalId?: number;
    hospitalName?: string;
    supplierId?: number;
    supplierName?: string;
    tanckerNumberPlate?:string,
    supplierType?: string;
    tripId?: number;
    trackingNo?: string;
    transactionsId?: number;
    sentTo?:String;
    comment?:String;//calculated
}
