/**
 * CovidCare API
 * CovidCare API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 import { TripDetailsDTO } from './tripDetailsDTO';


export interface TripDTO {
    id?: number;
    mobaId?: number;
    trackingNo?: string;
    numberPlate?: string;
    stock?: number;
    status?: string;
    createdDate?: Date;
    createdBy?: string;
    lastModified?: Date;
    lastModifiedBy?: string;
    supplierId?: number;
    supplierName: string;
    tripDetails?: Array<TripDetailsDTO>;
}
