/**
 * CovidCare API
 * CovidCare API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface VehiclesDTO {
  sr?: number;
  equipment?: string;
  uniqe_no?: number;
  imei_no?: number;
  number_plate?: string;
  date_time?: string;
  loc?: string;
  speed?: number;
  ignition?: number;
  latitude?: string;
  longitude?: string;
  mains?: number;
  gps?: string;
  fuel?: number;
  ibtn?: string;
}
